# Logiciels requis pour utiliser et travailler sur les documents du cours Info 111
name: info-111

channels:
- QuantStack
- conda-forge

dependencies:
- xeus-cling
- notebook
- nbgrader
- pandas         # for managing grades
- pip:
    - ordo
    - nbdime
    - .
#- matplotlib
#- cycler         # missing matplotlib dependecy: https://stackoverflow.com/questions/44419333/matplotlib-cant-find-cycler
#- xplot
